# Generated by Django 3.1.1 on 2020-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='markdown supported')),
                ('message_rendered', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
